### ISSUE TITLE
Could not find configuration in a property file for environment: development

### ISSUE THREAD

**Issue by scofier** [javalite/simple-example#3] opened 2016-11-24 10:43 UTC
Exception in thread "main" org.javalite.activejdbc.DBException: Could not find configuration in a property file for environment: development. Are you sure you have a database.properties file configured?
	at org.javalite.activejdbc.DB.open(DB.java:145)
	at org.javalite.activejdbc.Base.open(Base.java:52)
	at activejdbc.examples.simple.Main.main(Main.java:15)

**Comment by ipolevoy** [comment] 2016-11-24 19:05
@scofier , did you run instrumentation? It generates this file: http://javalite.io/instrumentation

**Comment by ipolevoy** [comment] 2016-11-24 19:10
@scofier if you are running from inside the IDE, first execute this on command line to run instrumentation: 

    mvn process-classes

**Comment by ipolevoy** [comment] 2016-11-24 19:13
@scofier  the same can be done like this: 

    mvn activejdbc-instrumentation:instrument

**Comment by ipolevoy** [comment] 2016-12-07 03:01
@scofier I changed versions of dependencies. Pull and try again - see the README file for step by step.

**Comment by amasscto** [comment] 2017-08-07 03:06
Hi Igor, I am running into this same issue while trying to use ActiveJDBC with AWS Lambda. I am trying to use the AWS Eclipse plugin to upload the code. Is there any known limitation with this approach? I am suspecting if this approach is overriding the instrumented classes. But no easy way for me to know hence reaching out to you.

**Comment by ipolevoy** [comment] 2017-08-07 03:08
@scofier ensure you run instrumentation and upload all instrumented classes as well as the property files generated by instrumentation.

**Comment by amasscto** [comment] 2017-08-07 03:47
Thank you so much for the quick reply. Well, the same approach worked for me when I tested the code locally. I do see the properties file when checked in the jar file which was uploaded to S3 but the error prevails. Even the instrumented classes are in place but to no avail. Do you happen to know if ActiveJDBC works in AWS Lambda? Has anyone else tried it before?

**Comment by ipolevoy** [comment] 2017-08-07 04:25
@amasscto I personally have not tried it. If you are getting the exception above, then clearly the generated file is missing. Is there anything special about AWS Lambda? Also, check this out, and see if it is related somehow: https://github.com/javalite/activejdbc/issues/479

**Comment by amasscto** [comment] 2017-08-07 13:06
@ipolevoy I can confirm that the database.properties is available in the classpath. The same folder has activejdbc_models.properties and the code could locate it. I was able to make it work by passing connection parameters to the method instead of just using Base.open(). 
Note that I was looking for replacing MyBatis with ActiveJDBC and running into this issue. 
MyBatis is working with AWS Lambda without any issue and it uses the classloader's getResourceAsStream.
So while I have a workaround, it would be best if the code could locate the properties file in AWS Lambda environment.

**Comment by ipolevoy** [comment] 2017-08-07 15:29
@amasscto I think you are confusing different things. `Base.open()` creates a connection and has nothing to do with `activejdbc_models.properties`. The file `activejdbc_models.properties` is generated by an instrumentation process and loaded by the framework when you use models. Generally, it is not touched by a developer. The method `Base.open()` opens a connection, and has a number of overloaded versions, where one uses a file `database.properties` for connection configuration according to the current environment.

**Comment by ipolevoy** [comment] 2017-08-07 15:31
@amasscto do not forget, that for `database.properties` to work, you need to set your `ACTIVE_ENV` variable accordingly: http://javalite.io/database_connection_management#multiple-environments-property-file-method

**Comment by amasscto** [comment] 2017-08-07 16:47
@ipolevoy I am using the default "development" environment so I did not set it, which is the same when I test locally without AWS Lambda. So we can rule out this case.

**Comment by ipolevoy** [comment] 2017-08-07 17:00
if DB class cannot find this file on classpath, then it is not available. Try writing just: 

    URL url =  myclass.getClass().getResource("/database.properties"); 

and see if you can even load the file.

**Comment by amasscto** [comment] 2017-08-08 03:55
@ipolevoy, I tried your suggestion and here is the interesting part, the file exists but still not being loaded.
The below logs are from the AWS Lambda execution.
The first two lines are generated from the below code.
```
System.out.println ("DB File: " + Base.class.getResource("/database.properties"));
File f = new File(Base.class.getResource("/database.properties").getFile());
if(f.exists()){
  System.out.println(f.getAbsolutePath() + " exists.");
}
else{
  System.out.println(f.getAbsolutePath() + " doesn't exists.");
}
```
03:46:58 DB File: file:/var/task/database.properties
03:46:58 /var/task/database.properties exists.
03:46:58 Could not find configuration in a property file for environment: development. Are you sure you have a database.properties file configured?: org.javalite.activejdbc.DBException org.javalite.activejdbc.DBException: Could not find configuration in a property file for environment: development. Are you sure you have a database.properties file configured? at org.javalite.activejdbc.DB.open(DB.java:151)

**Comment by ipolevoy** [comment] 2017-08-08 05:11
@amasscto this is odd. Can you include the content of your database.properties file (block passwords).

**Comment by amasscto** [comment] 2017-08-10 01:34
@ipolevoy here is the database.properties file:
```
development.driver=com.mysql.jdbc.Driver
development.username=xxxxx
development.password=xxxxx
development.url=jdbc:mysql://172.26.14.118/soc_dev?useSSL=false

development.test.driver=com.mysql.jdbc.Driver
development.test.username=xxxx
development.test.password=xxxx
development.test.url=jdbc:mysql://localhost/movies_test
```

**Comment by ipolevoy** [comment] 2017-08-10 03:07
@amasscto , this is looking normal. I can add debug statements to the SNAPSHOT code to trace where this file is loaded and what configurations are discovered in the file. What version are you using?

**Comment by amasscto** [comment] 2017-08-10 03:18
I am using 1.4.13.j7

**Comment by ipolevoy** [comment] 2017-08-10 03:37
Are you stuck on Java 7?

**Comment by amasscto** [comment] 2017-08-10 04:38
Nope, I am using Java 8.

**Comment by ipolevoy** [comment] 2017-08-10 04:47
you are using the last build for Java 7. Please, use the latest version 2.0-SNAPSHOT  from http://repo.javalite.io/. It might work the same, but at least I can add log statements to a snapshot

**Comment by douglasrlee** [comment] 2017-12-10 05:43
I am actually having the same exact issue as @amasscto.

`Base.open()` is not finding my `database.properties` file.  I also do not have `ACTIVE_ENV` set as I am doing this all on development right now.

My properties file looks like:
```
development.driver=org.postgresql.Driver
development.username=admin
development.password=password
development.url=jdbc:postgresql://localhost:5432/job_fair_development
```

I am using java 8 and activejdbc 1.4.13.

**Comment by ipolevoy** [comment] 2017-12-11 13:16
@douglasrlee what error are you getting?

**Comment by rivella50** [comment] 2018-02-25 19:55
I'm having the same issues for production environment. The error message is:
org.javalite.activejdbc.DBException: Could not find configuration in a property file for environment: production. Are you sure you have a database.properties file configured?

On the server i've set
```
ACTIVE_ENV=production
```
Instrumentation has been done. I upload one .jar file where i tried the following string in both files database.properties and activejdbc.properties in the root directory:
```
env.connections.file=/Volumes/JavaApplications/myapp/database.properties
```
The .jar file is in the same directory as the database.properties is.
I'm using Java 9 and ActiveJDBC version 2.0.
On my local development machine i can start the application and access the db.

**Comment by ipolevoy** [comment] 2018-02-25 20:49
Please package the file into a jar file, less configuration. Additionally, you need to provide 4 properties for each environment, unless you use jndi.

**Comment by ipolevoy** [comment] 2018-02-25 20:50
The whole idea is to have a single file that just works in every environment. I personally have the same version of everything in each environment to avoid weird issues.

**Comment by ipolevoy** [comment] 2018-02-25 20:51
I will reol

**Comment by ipolevoy** [comment] 2018-02-25 20:51
Oops... I will reopen this to add more debugging info to a log file

**Comment by rivella50** [comment] 2018-02-25 20:55
When i package the database.properties file on production into the jar file it works on production, but this is a nogo for our purposes. That file has to be outside of the jar file.

**Comment by rivella50** [comment] 2018-02-25 21:00
What's the filename meant to be which holds the line
```
env.connections.file=/Volumes/JavaApplications/myapp/database.properties
```
for production, activejdbc.properties or database.properties?
If it's the latter one, could it be that there is a mixup with the database.properties which lies on the production server and which holds the 4 properties?

**Comment by ipolevoy** [comment] 2018-02-26 05:47
@rivella50 , do not use the `activejdbc.properties` unless you need to mess with behavior of the framework. The file to configure database connections for different environments is `database.properties`.

**Comment by rivella50** [comment] 2018-02-26 06:39
Ok i did that all, the error message stays the same.
To me it looks like that the entry
```
env.connections.file=/Volumes/JavaApplications/myapp/database.properties
```
is not handled correctly in the database.properties which is included in the jar file. All seems to be at its place and with the same content which works if i put the production database.properties into the jar directly.

**Comment by rivella50** [comment] 2018-02-26 06:49
My test main class looks like this:
```
Base.open();
List<Channel> channels = Channel.findAll();
System.out.println("channels size: " +channels.size());
Base.close();
```

**Comment by ipolevoy** [comment] 2018-02-26 13:43
how do  you supply `env.connections.file` to the app?

**Comment by rivella50** [comment] 2018-02-26 13:49
It's in database.properties (one line only for production environment) which is located in src/main/resources.

**Comment by ipolevoy** [comment] 2018-02-26 14:37
@rivella50 what is that line? Also, if the file is packaged in the jar file, you do not need `env.connections.file`.

**Comment by rivella50** [comment] 2018-02-26 15:25
In database.properties in the jar i have
```
env.connections.file=/Volumes/JavaApplications/myapp/database.properties
```
which points to the file which contains the 4 production properties.
As mentioned we cannot put that database.properties in the jar file.

**Comment by ipolevoy** [comment] 2018-02-26 15:43
@rivella50, this absolutely makes no sense. Please, read the docs. The file `database.properties` is for database connection properties. The location of this file can be augmented by adding a System property `env.connections.file` that points to a file on your file system. The file `database.properties` must have proper database connection parameters for your database and environment as described: http://javalite.io/database_connection_management#multiple-environments-property-file-method

**Comment by ipolevoy** [comment] 2018-02-26 15:44
so, call your program: 

    java yourMainProg -Denv.connections.file=/Volumes/JavaApplications/myapp/database.properties

**Comment by rivella50** [comment] 2018-02-26 15:56
Actually i thought i could do this approach: http://javalite.io/database_connection_management#location-of-property-file
and i think i did that correctly.

**Comment by ipolevoy** [comment] 2018-02-26 16:08
@rivella50 I see. Looks like this is an error  in the doc, sorry. I will fix the docs, but in the mean time, configure the app as I described above.

**Comment by rivella50** [comment] 2018-02-26 16:21
Ah, ok, then i will do that approach.
Nevertheless i would like the way described by entering the env.connections.file line in activejdbc.properties (or any other file) and keep that inside the jar file.

**Comment by rivella50** [comment] 2018-02-26 20:58
Hmmmmm, i've changed as told but the error message stays the same.
I call now the application with
```
java com.my.path.Main -cp my.jar -Denv.connections.file=/Volumes/JavaApplications/myapp/database.properties  
```
The properties file is at the given location. No properties file anymore in the jar file.

**Comment by ipolevoy** [comment] 2018-02-26 21:46
@rivella50 I confused myself and you too, sorry. I filed a bug: https://github.com/javalite/activejdbc/issues/681. It will get fixed soon, and I will let you know

**Comment by ipolevoy** [comment] 2018-02-27 05:35
@rivella50 , this  got fixed in a snapshot version 2.1.-SNAPSHOT. This should now be working: 

    java com.my.path.Main -cp my.jar -Denv.connections.file=/Volumes/JavaApplications/myapp/database.properties  

In fact, any property from `activejdbc.properties` file can be overridden from a system property.

**Comment by rivella50** [comment] 2018-02-27 08:29
You're right, now it works with both an entry in activejdbc.properties and the system property as well on production. Thanks for the fix.
Will there be a 2.1 release soon?

**Comment by ipolevoy** [comment] 2018-02-28 23:59
@rivella50 it is hard to tell. Normally as the number of new features and bugs get fixed, we majke a decision to cut a new release. There is no set schedule though. The 2.0 got released a few weeks ago. Are you not comfortable to glide in a SNAPSHOT? Just so you know, my commercial projects are always running in snapshots.

**Closed as completed by ipolevoy** 2018-02-28 23:59 UTC

**Comment by hpeevmb** [comment] 2018-08-20 16:07
Hello, 

If I understand correctly this issue is fixed in release activejdbc-root-2.1.

When do you plan to make it available for download as maven plugin?

https://mvnrepository.com/artifact/org.javalite/activejdbc

**Comment by ipolevoy** [comment] 2018-08-20 16:13
@hpeevmb , the version 2.1 has not yet been released. However, will be releasing this week

**Comment by hpeevmb** [comment] 2018-08-20 16:21
Great, thanks!
