### ISSUE TITLE
why i can not instrumentation with Maven plugin?

### ISSUE THREAD

**Issue by Theone21** [javalite/simple-example#5] opened 2018-08-09 05:22 UTC
when i execute "mvn activejdbc-instrumentation:instrument" this errror happpens :
 ```
[ERROR] Failed to execute goal org.javalite:activejdbc-instrumentation:2.0:instr
ument (default-cli) on project simple-example: Failed to add output directory to
 classpath: org.javalite.instrumentation.InstrumentationException: java.lang.Run
timeException: cannot find dependency.com.mysql.fabric.FabricCommunicationExcept
ion: com.mysql.fabric.FabricCommunicationException found in dependency/com/mysql
/fabric/FabricCommunicationException.class -> [Help 1]
```

**Comment by ipolevoy** [comment] 2018-08-09 14:04
@Theone21 seems this is a dependency issue not having to do with the Instrumentation. 

I made a small change in dependencies, please get new code and try again. Closing because this is not a bug, but you can continue comments.

**Closed as completed by ipolevoy** 2018-08-09 14:04 UTC
